# Generated by Django 5.2.5 on 2025-11-24 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_customer_budget_booking_customer_email_and_more'),
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_budget',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event_location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or requirements from the client'),
        ),
    ]
