# Generated by Django 5.2.5 on 2025-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('vendors', '0002_vendor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='services.servicecategory'),
        ),
    ]
