# Generated by Django 5.2.5 on 2025-11-20 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_covers/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='VendorPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vendor_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='vendors.vendor')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
