# Generated by Django 5.2.5 on 2025-11-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_social_media_and_gallery'),
        ('vendors', '0004_vendor_cover_photo_vendor_facebook_url_and_more'),
    ]

    operations = [
    ]
