# Generated by Django 5.2.5 on 2025-11-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_merge_20251121_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-created_at']},
        ),
    ]
