# Generated by Django 5.2.5 on 2025-11-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_vendor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='cover_photo',
        ),
    ]
