# Generated by Django 5.2.5 on 2025-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_remove_vendor_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_covers/'),
        ),
    ]
